Add Task Manager project
Funiusa/djangoTaskManager pull request #1
Opened 2023-02-04 13:57 UTC by Funiusa

There is a base Dockerfile in main directory created for python3.9-slib-buster. Becouse oficial version doesn't work.
Inside the TaskManager dir there is another Dockerfile, created already for task_manajer project.
In this stage need at first do build the base Dockerfile and next build the Dockerfile inside TaskManager dir.

2023-02-07 02:44 UTC, aleksandr-semenov-dbp requested changes

2023-02-07 02:44 UTC, aleksandr-semenov-dbp commented on Dockerfile
> +
Давай обойдемся без этого докерфайла. Только с готовым питоном (и вытащим его в корень). Почему второй без него не собирается? В крайнем случае попробуй какие-то соседние похожие имиджи с другой версией питона

2023-02-07 10:51 UTC, Funiusa commented on Dockerfile
> +
Почему то в первый раз сборка не могла скачать с репозитория базовый Python образ. Пробовал разные, ни один не работал и пришлось подключить другой. Сейчас все работает.

2023-02-08 11:30 UTC, aleksandr-semenov-dbp approved these changes

2023-02-10 09:50 UTC, merged