Add tests with ActionClient
Funiusa/djangoTaskManager pull request #45
Opened 2023-05-09 08:37 UTC by Funiusa

2023-05-15 08:58 UTC, aleksandr-semenov-dbp requested changes

2023-05-15 08:58 UTC, aleksandr-semenov-dbp commented on TaskManager/test/base.py
> +        response = self.request_list(args)
Здесь в отличие от request_ мы еще проверяем успешный код статуса (в retrieve и delete тоже)

2023-05-15 08:58 UTC, aleksandr-semenov-dbp commented on TaskManager/test/test_tag.py
> +        self.assertEqual(response.status_code, status.HTTP_200_OK)
используем гораздо более продвинутый pytest, не нужен этот assertEqual() просто assert x == y

2023-05-15 08:58 UTC, aleksandr-semenov-dbp commented on TaskManager/test/test_tag.py
не достаточно проверить код, надо проверять содержимое

2023-05-17 08:00 UTC, aleksandr-semenov-dbp requested changes

2023-05-17 08:00 UTC, aleksandr-semenov-dbp commented on TaskManager/test/test_task.py
> +        assert response.status_code == status.HTTP_200_OK
Это теперь не нужно проверять (проверка есть внутри list()) а вот содержимое проверить надо

2023-05-17 08:00 UTC, aleksandr-semenov-dbp commented on TaskManager/test/test_task.py
> +        assert qs.count() == 2
Нет, фильтры тестируем не так, используем метод черного ящика, обращаемся через api и смотрим содержимое результата. (Надо добавить в list() возможность включать дополнительные параметры в запрос client.get())

2023-05-17 17:00 UTC, Funiusa commented on TaskManager/test/test_task.py
> +        assert response.status_code == status.HTTP_200_OK
Случайно пропустил)

2023-05-29 12:46 UTC, kirill-gorshkov requested changes

2023-05-29 12:46 UTC, kirill-gorshkov commented on TaskManager/test/test_tag.py
> +            self.tag_attributes["title"] = title
Не стоит менять в результате работы фабрики какие-либо данные.
Если нужны какие-то данные для тестов, то стоит нагенерировать новые.

2023-06-02 06:35 UTC, aleksandr-semenov-dbp approved these changes

2023-06-02 07:55 UTC, merged